version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd frontend-new
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: frontend-new/dist
    files:
      - '**/*'
  cache:
    paths:
      - frontend-new/node_modules/**/*