# Docker Compose override for HTTP service mode
version: '3.8'

services:
  whisper-http-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classreflect-whisper-http
    environment:
      # Service mode configuration
      - SERVICE_MODE=http
      - USE_LOCAL_DB=${USE_LOCAL_DB:-true}
      
      # Whisper configuration
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      
      # Local database configuration
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-classreflect}
      
    volumes:
      # Mount local audio files directory (read-only)
      - ${LOCAL_AUDIO_DIR:-/tmp/classreflect-audio}:/tmp/audio:ro
      # Mount for model caching
      - whisper_models:/root/.cache/whisper
      
    ports:
      - "8000:8000"
      
    networks:
      - classreflect
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Override the default command to run HTTP service
    command: ["python", "whisper_service.py"]

volumes:
  whisper_models:

networks:
  classreflect:
    driver: bridge