version: '3.8'

services:
  whisper-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classreflect-whisper
    environment:
      # Mode configuration
      - USE_AWS=${USE_AWS:-false}
      - USE_LOCAL_DB=${USE_LOCAL_DB:-true}
      
      # Whisper configuration
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - MAX_EMPTY_POLLS=${MAX_EMPTY_POLLS:-10}
      
      # AWS configuration (only used if USE_AWS=true)
      - AWS_REGION=${AWS_REGION:-eu-west-2}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SQS_QUEUE_URL=${SQS_QUEUE_URL:-https://sqs.eu-west-2.amazonaws.com/573524060586/classreflect-processing-queue}
      - S3_BUCKET=${S3_BUCKET:-classreflect-audio-files-573524060586}
      - DB_SECRET_ARN=${DB_SECRET_ARN}
      
      # Local database configuration (used if USE_LOCAL_DB=true)
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - DB_NAME=${DB_NAME:-classreflect}
      
      # Local files directory
      - LOCAL_FILES_DIR=/opt/audio_files
      
    volumes:
      # Mount local audio files directory
      - ${LOCAL_AUDIO_DIR:-./audio_files}:/opt/audio_files
      # Mount for model caching
      - whisper_models:/home/whisperuser/.cache/whisper
      
    networks:
      - classreflect
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Optional: Local MySQL database for testing
  mysql:
    image: mysql:8.0
    container_name: classreflect-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_NAME:-classreflect}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - classreflect
    restart: unless-stopped
    profiles:
      - local-db

volumes:
  whisper_models:
  mysql_data:

networks:
  classreflect:
    driver: bridge